# Generated by Django 3.0.5 on 2020-07-03 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200703_0119'),
        ('home', '0002_auto_20200703_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Used - Like New'), (2, 'Used - Good'), (4, 'Used - Not Usable'), (3, 'Used - Poor Condidtion'), (0, 'Brand New')], default=4),
        ),
    ]
