# Generated by Django 3.0.5 on 2020-07-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200712_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.IntegerField(choices=[(3, 'Used - Poor Condidtion'), (0, 'Brand New'), (4, 'Used - Not Usable'), (2, 'Used - Good'), (1, 'Used - Like New')], default=4),
        ),
    ]
