# Generated by Django 3.0.5 on 2020-07-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200713_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.IntegerField(choices=[(4, 'Used - Not Usable'), (1, 'Used - Like New'), (3, 'Used - Poor Condidtion'), (2, 'Used - Good'), (0, 'Brand New')], default=4),
        ),
    ]
