# Generated by Django 3.0.5 on 2020-07-03 05:16

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField(max_length=300, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.IntegerField(choices=[(0, 'Electronic'), (1, 'Furniture'), (2, 'Major Appliance'), (3, 'Kitchen'), (4, 'Books'), (5, 'Motors'), (6, 'Music'), (7, 'Other')], default=0)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('item_label', models.CharField(choices=[(0, 'Best-Seller'), (1, 'Must Have'), (2, 'durable'), (3, 'Best Bang for your buck'), (4, 'Pollitzer Award')], default=0, max_length=100)),
                ('condition', models.IntegerField(choices=[(3, 'Used - Poor Condidtion'), (0, 'Brand New'), (1, 'Used - Like New'), (4, 'Used - Not Usable'), (2, 'Used - Good')], default=4)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(9999999999)])),
                ('publish', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
