# Generated by Django 3.0.5 on 2020-07-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200703_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='item_label',
        ),
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(2, 'Used - Good'), (1, 'Used - Like New'), (3, 'Used - Poor Condidtion'), (4, 'Used - Not Usable'), (0, 'Brand New')], default=4),
        ),
    ]
