# Generated by Django 3.0.5 on 2020-07-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200712_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(4, 'Used - Not Usable'), (0, 'Brand New'), (3, 'Used - Poor Condidtion'), (2, 'Used - Good'), (1, 'Used - Like New')], default=4),
        ),
    ]
