# Generated by Django 3.0.5 on 2020-07-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20200713_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(0, 'Brand New'), (2, 'Used - Good'), (1, 'Used - Like New'), (4, 'Used - Not Usable'), (3, 'Used - Poor Condidtion')], default=4),
        ),
    ]
