# Generated by Django 3.0.5 on 2020-07-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20200720_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Used - Like New'), (0, 'Brand New'), (4, 'Used - Not Usable'), (2, 'Used - Good'), (3, 'Used - Poor Condidtion')], default=4),
        ),
    ]
