# Generated by Django 3.0.5 on 2020-07-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_auto_20200720_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(2, 'Used - Good'), (1, 'Used - Like New'), (4, 'Used - Not Usable'), (3, 'Used - Poor Condidtion'), (0, 'Brand New')], default=4),
        ),
    ]
