# Generated by Django 3.0.5 on 2020-07-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_auto_20200720_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Used - Like New'), (3, 'Used - Poor Condidtion'), (4, 'Used - Not Usable'), (2, 'Used - Good'), (0, 'Brand New')], default=4),
        ),
    ]
