# Generated by Django 3.0.5 on 2020-07-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0035_auto_20200720_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(3, 'Used - Poor Condidtion'), (4, 'Used - Not Usable'), (0, 'Brand New'), (2, 'Used - Good'), (1, 'Used - Like New')], default=4),
        ),
    ]
